export { default as Header } from './header/header.component';
export { default as CustomToggle } from './custom-toggle/custom-toggle.component';
export { default as ColorPicker } from './color-picker/color-picker.component';
export { default as ClaimItem } from './claim-item/claim-item.component';
export { default as FontSizer } from './font-sizer/font-sizer.component';
export { default as ActivityPane } from './activity-pane/activity-pane.component';
export { default as CommentItem } from './comment-item/comment-item.component';
export { default as EvidenceTab } from './evidence-tab/evidence-tab.component';
export { default as PlaceHolderImage } from './placeholder-image/placeholder-image.component';
export { default as ListLayout } from './list-view/list-layout/list-layout.component';
export { default as ColumnLayout } from './column-view/column-layout/column-layout.component';
export { default as CardLayout } from './card-view/card-layout/card-layout.component';
export { default as LayoutOps } from './layout-opts/layout-opts.component';
export { default as ProductParty } from './product-party/product-party.component';
export { default as AssertClaims } from './assert-claims/assert-claims.component';
export { default as Resizable } from './resizable/resizable.component';
export { default as ConfirmationPopup } from './confirmation-popup/confirmation-popup.component';
export { default as EditEvidence } from './edit-evidence/edit-evidence.component';

// export { default as EditClaims } from './edit-claims/edit-claims.component';
